name: Build App

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build the app
              run: bun run build
